config/routes.rb
Yield::Application.routes.draw do
  resources :score_cards

  resources :pycontextnlp_results

  resources :radiologists

  resources :exam_codes

  resources :requesting_mds

  resources :attendings

  resources :reports

end

app/models/exam_code.rb
class ExamCode < ActiveRecord::Base
  attr_accessible :name
  
  has_many :reports
  
	def self.score
		ExamCode.all.each{|examcode|
			score = 0
			examcode.reports.each{|report|
				puts report.id
				if report.positivity != nil
					score = score + report.positivity.classification
				else
					next
				end
			}
			examcode.total = examcode.reports.length
			examcode.score = Float(score)/Float(examcode.reports.length)
			examcode.save
		}
  end
  
  def positiveReports
		return self.reports.where(:positivity => 1)
  end
 
end

app/controllers/exam_codes_controller.rb
class ExamCodesController < ApplicationController
  # GET /exam_codes
  # GET /exam_codes.json
  def index
    @exam_codes = ExamCode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exam_codes }
    end
  end

  # GET /exam_codes/1
  # GET /exam_codes/1.json
  def show
    @exam_code = ExamCode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exam_code }
    end
  end

  # GET /exam_codes/new
  # GET /exam_codes/new.json
  def new
    @exam_code = ExamCode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exam_code }
    end
  end

  # GET /exam_codes/1/edit
  def edit
    @exam_code = ExamCode.find(params[:id])
  end

  # POST /exam_codes
  # POST /exam_codes.json
  def create
    @exam_code = ExamCode.new(params[:exam_code])

    respond_to do |format|
      if @exam_code.save
        format.html { redirect_to @exam_code, notice: 'Exam code was successfully created.' }
        format.json { render json: @exam_code, status: :created, location: @exam_code }
      else
        format.html { render action: "new" }
        format.json { render json: @exam_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exam_codes/1
  # PUT /exam_codes/1.json
  def update
    @exam_code = ExamCode.find(params[:id])

    respond_to do |format|
      if @exam_code.update_attributes(params[:exam_code])
        format.html { redirect_to @exam_code, notice: 'Exam code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exam_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exam_codes/1
  # DELETE /exam_codes/1.json
  def destroy
    @exam_code = ExamCode.find(params[:id])
    @exam_code.destroy

    respond_to do |format|
      format.html { redirect_to exam_codes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/exam_codes_helper.rb
module ExamCodesHelper
end

app/views/exam_codes/_form.html.erb
<%= form_for(@exam_code) do |f| %>
  <% if @exam_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam_code.errors.count, "error") %> prohibited this exam_code from being saved:</h2>

      <ul>
      <% @exam_code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exam_codes/edit.html.erb
<h1>Editing exam_code</h1>

<%= render 'form' %>

<%= link_to 'Show', @exam_code %> |
<%= link_to 'Back', exam_codes_path %>

app/views/exam_codes/index.html.erb
<h1>Listing exam_codes</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exam_codes.each do |exam_code| %>
  <tr>
    <td><%= exam_code.name %></td>
    <td><%= link_to 'Show', exam_code %></td>
    <td><%= link_to 'Edit', edit_exam_code_path(exam_code) %></td>
    <td><%= link_to 'Destroy', exam_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exam code', new_exam_code_path %>

app/views/exam_codes/new.html.erb
<h1>New exam_code</h1>

<%= render 'form' %>

<%= link_to 'Back', exam_codes_path %>

app/views/exam_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @exam_code.name %>
</p>


<%= link_to 'Edit', edit_exam_code_path(@exam_code) %> |
<%= link_to 'Back', exam_codes_path %>