config/routes.rb
Yield::Application.routes.draw do
  resources :score_cards

  resources :pycontextnlp_results

  resources :radiologists

  resources :exam_codes

  resources :requesting_mds

  resources :attendings

  resources :reports

end

app/models/score_card.rb
class ScoreCard < ActiveRecord::Base
  attr_accessible :exam_code_id, :gradeable, :gradeable_type, :score, :total
  
  belongs_to :gradeable, :polymorphic => true
  
end

app/controllers/score_cards_controller.rb
class ScoreCardsController < ApplicationController
  # GET /score_cards
  # GET /score_cards.json
  def index
    @score_cards = ScoreCard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @score_cards }
    end
  end

  # GET /score_cards/1
  # GET /score_cards/1.json
  def show
    @score_card = ScoreCard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @score_card }
    end
  end

  # GET /score_cards/new
  # GET /score_cards/new.json
  def new
    @score_card = ScoreCard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @score_card }
    end
  end

  # GET /score_cards/1/edit
  def edit
    @score_card = ScoreCard.find(params[:id])
  end

  # POST /score_cards
  # POST /score_cards.json
  def create
    @score_card = ScoreCard.new(params[:score_card])

    respond_to do |format|
      if @score_card.save
        format.html { redirect_to @score_card, notice: 'Score card was successfully created.' }
        format.json { render json: @score_card, status: :created, location: @score_card }
      else
        format.html { render action: "new" }
        format.json { render json: @score_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /score_cards/1
  # PUT /score_cards/1.json
  def update
    @score_card = ScoreCard.find(params[:id])

    respond_to do |format|
      if @score_card.update_attributes(params[:score_card])
        format.html { redirect_to @score_card, notice: 'Score card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @score_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /score_cards/1
  # DELETE /score_cards/1.json
  def destroy
    @score_card = ScoreCard.find(params[:id])
    @score_card.destroy

    respond_to do |format|
      format.html { redirect_to score_cards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/score_cards_helper.rb
module ScoreCardsHelper
end

app/views/score_cards/_form.html.erb
<%= form_for(@score_card) do |f| %>
  <% if @score_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score_card.errors.count, "error") %> prohibited this score_card from being saved:</h2>

      <ul>
      <% @score_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :total %><br />
    <%= f.number_field :total %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :exam_code_id %><br />
    <%= f.number_field :exam_code_id %>
  </div>
  <div class="field">
    <%= f.label :gradeable %><br />
    <%= f.number_field :gradeable %>
  </div>
  <div class="field">
    <%= f.label :gradeable_type %><br />
    <%= f.text_field :gradeable_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/score_cards/edit.html.erb
<h1>Editing score_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @score_card %> |
<%= link_to 'Back', score_cards_path %>

app/views/score_cards/index.html.erb
<h1>Listing score_cards</h1>

<table>
  <tr>
    <th>Total</th>
    <th>Score</th>
    <th>Exam code</th>
    <th>Gradeable</th>
    <th>Gradeable type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @score_cards.each do |score_card| %>
  <tr>
    <td><%= score_card.total %></td>
    <td><%= score_card.score %></td>
    <td><%= score_card.exam_code_id %></td>
    <td><%= score_card.gradeable %></td>
    <td><%= score_card.gradeable_type %></td>
    <td><%= link_to 'Show', score_card %></td>
    <td><%= link_to 'Edit', edit_score_card_path(score_card) %></td>
    <td><%= link_to 'Destroy', score_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Score card', new_score_card_path %>

app/views/score_cards/new.html.erb
<h1>New score_card</h1>

<%= render 'form' %>

<%= link_to 'Back', score_cards_path %>

app/views/score_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Total:</b>
  <%= @score_card.total %>
</p>

<p>
  <b>Score:</b>
  <%= @score_card.score %>
</p>

<p>
  <b>Exam code:</b>
  <%= @score_card.exam_code_id %>
</p>

<p>
  <b>Gradeable:</b>
  <%= @score_card.gradeable %>
</p>

<p>
  <b>Gradeable type:</b>
  <%= @score_card.gradeable_type %>
</p>


<%= link_to 'Edit', edit_score_card_path(@score_card) %> |
<%= link_to 'Back', score_cards_path %>