config/routes.rb
Yield::Application.routes.draw do
  resources :score_cards

  resources :pycontextnlp_results

  resources :radiologists

  resources :exam_codes

  resources :requesting_mds

  resources :attendings

  resources :reports

end

app/models/pycontextnlp_result.rb
class PycontextnlpResult < ActiveRecord::Base
  attr_accessible :classification, :most_positive_target, :report_number, :run_args, :schema, :target_category
  
	belongs_to :report, :foreign_key => "report_number"
  
end

app/controllers/pycontextnlp_results_controller.rb
class PycontextnlpResultsController < ApplicationController
  # GET /pycontextnlp_results
  # GET /pycontextnlp_results.json
  def index
    @pycontextnlp_results = PycontextnlpResult.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pycontextnlp_results }
    end
  end

  # GET /pycontextnlp_results/1
  # GET /pycontextnlp_results/1.json
  def show
    @pycontextnlp_result = PycontextnlpResult.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pycontextnlp_result }
    end
  end

  # GET /pycontextnlp_results/new
  # GET /pycontextnlp_results/new.json
  def new
    @pycontextnlp_result = PycontextnlpResult.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pycontextnlp_result }
    end
  end

  # GET /pycontextnlp_results/1/edit
  def edit
    @pycontextnlp_result = PycontextnlpResult.find(params[:id])
  end

  # POST /pycontextnlp_results
  # POST /pycontextnlp_results.json
  def create
    @pycontextnlp_result = PycontextnlpResult.new(params[:pycontextnlp_result])

    respond_to do |format|
      if @pycontextnlp_result.save
        format.html { redirect_to @pycontextnlp_result, notice: 'Pycontextnlp result was successfully created.' }
        format.json { render json: @pycontextnlp_result, status: :created, location: @pycontextnlp_result }
      else
        format.html { render action: "new" }
        format.json { render json: @pycontextnlp_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pycontextnlp_results/1
  # PUT /pycontextnlp_results/1.json
  def update
    @pycontextnlp_result = PycontextnlpResult.find(params[:id])

    respond_to do |format|
      if @pycontextnlp_result.update_attributes(params[:pycontextnlp_result])
        format.html { redirect_to @pycontextnlp_result, notice: 'Pycontextnlp result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pycontextnlp_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pycontextnlp_results/1
  # DELETE /pycontextnlp_results/1.json
  def destroy
    @pycontextnlp_result = PycontextnlpResult.find(params[:id])
    @pycontextnlp_result.destroy

    respond_to do |format|
      format.html { redirect_to pycontextnlp_results_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pycontextnlp_results_helper.rb
module PycontextnlpResultsHelper
end

app/views/pycontextnlp_results/_form.html.erb
<%= form_for(@pycontextnlp_result) do |f| %>
  <% if @pycontextnlp_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pycontextnlp_result.errors.count, "error") %> prohibited this pycontextnlp_result from being saved:</h2>

      <ul>
      <% @pycontextnlp_result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :report_number %><br />
    <%= f.number_field :report_number %>
  </div>
  <div class="field">
    <%= f.label :run_args %><br />
    <%= f.number_field :run_args %>
  </div>
  <div class="field">
    <%= f.label :schema %><br />
    <%= f.number_field :schema %>
  </div>
  <div class="field">
    <%= f.label :target_category %><br />
    <%= f.text_area :target_category %>
  </div>
  <div class="field">
    <%= f.label :classification %><br />
    <%= f.number_field :classification %>
  </div>
  <div class="field">
    <%= f.label :most_positive_target %><br />
    <%= f.text_area :most_positive_target %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pycontextnlp_results/edit.html.erb
<h1>Editing pycontextnlp_result</h1>

<%= render 'form' %>

<%= link_to 'Show', @pycontextnlp_result %> |
<%= link_to 'Back', pycontextnlp_results_path %>

app/views/pycontextnlp_results/index.html.erb
<h1>Listing pycontextnlp_results</h1>

<table>
  <tr>
    <th>Report number</th>
    <th>Run args</th>
    <th>Schema</th>
    <th>Target category</th>
    <th>Classification</th>
    <th>Most positive target</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pycontextnlp_results.each do |pycontextnlp_result| %>
  <tr>
    <td><%= pycontextnlp_result.report_number %></td>
    <td><%= pycontextnlp_result.run_args %></td>
    <td><%= pycontextnlp_result.schema %></td>
    <td><%= pycontextnlp_result.target_category %></td>
    <td><%= pycontextnlp_result.classification %></td>
    <td><%= pycontextnlp_result.most_positive_target %></td>
    <td><%= link_to 'Show', pycontextnlp_result %></td>
    <td><%= link_to 'Edit', edit_pycontextnlp_result_path(pycontextnlp_result) %></td>
    <td><%= link_to 'Destroy', pycontextnlp_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pycontextnlp result', new_pycontextnlp_result_path %>

app/views/pycontextnlp_results/new.html.erb
<h1>New pycontextnlp_result</h1>

<%= render 'form' %>

<%= link_to 'Back', pycontextnlp_results_path %>

app/views/pycontextnlp_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Report number:</b>
  <%= @pycontextnlp_result.report_number %>
</p>

<p>
  <b>Run args:</b>
  <%= @pycontextnlp_result.run_args %>
</p>

<p>
  <b>Schema:</b>
  <%= @pycontextnlp_result.schema %>
</p>

<p>
  <b>Target category:</b>
  <%= @pycontextnlp_result.target_category %>
</p>

<p>
  <b>Classification:</b>
  <%= @pycontextnlp_result.classification %>
</p>

<p>
  <b>Most positive target:</b>
  <%= @pycontextnlp_result.most_positive_target %>
</p>


<%= link_to 'Edit', edit_pycontextnlp_result_path(@pycontextnlp_result) %> |
<%= link_to 'Back', pycontextnlp_results_path %>