config/routes.rb
Yield::Application.routes.draw do
  resources :score_cards

  resources :pycontextnlp_results

  resources :radiologists

  resources :exam_codes

  resources :requesting_mds

  resources :attendings

  resources :reports

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Yield" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Yield</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Reports", reports_path  %></li>
              <li><%= link_to "Radiologists", radiologists_path  %></li>
              <li><%= link_to "Requesting MD", requesting_mds_path  %></li>
              <li><%= link_to "Attending", attendings_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Totals</h3>
              <ul class="nav nav-list">
                <li class="nav-header"></li>
                <li></li>
                <li></li>
                <li></li>
              </ul>
              <% ExamCode.all.each do |examcode| %>
				Name: <%= examcode.name %> <br/>
				Positive: <%= examcode.score %> <br />
				Total <%= examcode.total %>
			  <% end %>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Big Brother 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>